name: rag-llm-demo-ui
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - pip
  - pip-tools
  - pip:
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asyncpg==0.30.0
      - azure-core==1.35.1
      - azure-identity==1.25.1
      - beautifulsoup4==4.14.2
      - brotli==1.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cryptography==46.0.2
      - elastic-transport==8.17.1
      - elasticsearch[vectorstore-mmr]==8.19.1
      - fastapi==0.119.0
      - ffmpy==0.6.3
      - filelock==3.20.0
      - fsspec==2025.9.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - greenlet==3.2.4
      - groovy==0.1.2
      - grpcio==1.75.1
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.1.10
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx[http2]==0.28.1
      - huggingface-hub==0.35.3
      - hyperframe==6.1.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpath-ng==1.7.0
      - jsonpointer==3.0.0
      - langchain==0.3.27
      - langchain-core==0.3.79
      - langchain-elasticsearch==0.3.2
      - langchain-huggingface==0.3.1
      - langchain-postgres==0.0.15
      - langchain-qdrant==0.2.1
      - langchain-redis==0.2.4
      - langchain-sqlserver==0.1.2
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.35
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - multidict==6.7.0
      - networkx==3.5
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.3
      - pgvector==0.3.6
      - pillow==11.3.0
      - ply==3.11
      - portalocker==3.2.0
      - propcache==0.4.1
      - protobuf==6.32.1
      - psycopg==3.2.10
      - psycopg-binary==3.2.10
      - psycopg-pool==3.2.6
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyjwt[crypto]==2.10.1
      - pyodbc==5.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - python-ulid==3.1.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - qdrant-client==1.15.1
      - redis==6.4.0
      - redisvl==0.9.1
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - ruff==0.14.0
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - semantic-version==2.10.0
      - sentence-transformers==5.1.1
      - shellingham==1.5.4
      - simsimd==6.5.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - starlette==0.48.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.4.0
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - websockets==15.0.1
      - yarl==1.22.0
      - zstandard==0.25.0
